apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yx6xwtprr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yx6xwtprr-python 
  name: yx6xwtprr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yx6xwtprr-python 
